<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.4 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 10748 2007-10-10 07:30:59Z cybot_tm $
 * Date: Fri, 22 Feb 2008 19:49:15 GMT
 */

/* Servers configuration */
$i = 0;

/* Server ARIS Database (config:aris) [1] */
$i++;
$cfg['Servers'][$i]['bookmarktable'] = 'pma_bookmark';
$cfg['Servers'][$i]['relation'] = 'pma_relation';
$cfg['Servers'][$i]['table_info'] = 'pma_table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma_table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma_pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma_column_info';
$cfg['Servers'][$i]['designer_coords'] = 'pma_designer_coords';
$cfg['Servers'][$i]['history'] = 'pma_history';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'arisuser';
$cfg['Servers'][$i]['password'] = 'arispwd';
$cfg['Servers'][$i]['only_db'] = 'aris';

$cfg['Servers'][$i]['verbose'] = 'Madison Game - ARIS';
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';

/* End of servers configuration */

$cfg['UploadDir'] = 'uploads';
$cfg['SaveDir'] = 'saves';
$cfg['LeftDisplayLogo'] = FALSE;
$cfg['MaxRows'] = 500;
$cfg['DefaultTabTable'] = 'sql.php';
$cfg['ThemeDefault'] = 'darkblue_orange';
$cfg['LeftFrameLight'] = TRUE;
$cfg['ShowAll']  = TRUE;
?>
